train_dir: "./datas_no_hyphen/train/"
valid_dir: "./datas_no_hyphen/valid/"
test_dir: "./datas_no_hyphen/valid/"
saving_ckpt: "saving_ckpt-vietnam"
img_size: !!python/tuple [100, 50]
dropout_rate: 0.5
weight_decay: 0.00002
lr: 0.001
batch_size: 32
t_length: 19
gradient_clip_val: 1.0
chars: [
    # NUMBERS
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    # ALPHABETS
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "K",
    "L",
    "M",
    "N",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "X",
    "Y",
    "Z",
    "Đ",
    # Middle
    "-",
    "_", # CTC Blank Token
  ]
